# Generated by Django 5.1.5 on 2025-02-16 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('due_date', models.DateField(verbose_name='Дата выполнения')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.todolist')),
            ],
        ),
    ]
